import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Sidebar from "@/components/Sidebar";
import { Protest_Riot, Jersey_15 } from "next/font/google";
import { Toaster } from "react-hot-toast";

const protest = Protest_Riot({
  subsets: ["latin"],
  weight: "400",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={protest.className}>
        <div className="w-full flex bg-blue-100">
          <Toaster />
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
